// Builds review/index.html: every question, option points, and EVERY distinct result each quiz can produce (brute-force enumeration).
import fs from 'fs';
const slugs=['pad','vein','ufe','aaa','gae','carotid']; const esc=s=>String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;');
let out='';
for(const slug of slugs){
  const html=fs.readFileSync(`${slug}/index.html`,'utf8'); const cfgSrc=html.match(/<script>\n([\s\S]*?)\n<\/script>/)[1]; const title=html.match(/<h1>(.*?)<\/h1>/)[1];
  const window={}; eval(cfgSrc); const cfg=window.VVIS_QUIZ; const Q=cfg.questions;
  // per-question choice sets: single -> index list; multi -> all subsets honoring 'none' exclusivity
  const choiceSets=Q.map(q=>{ if(!q.multi) return q.opts.map((_,k)=>[k]); const normal=q.opts.map((_,k)=>k).filter(k=>q.opts[k][2]!=='none'); const none=q.opts.map((_,k)=>k).filter(k=>q.opts[k][2]==='none'); const subsets=[]; for(let m=1;m<(1<<normal.length);m++){ subsets.push(normal.filter((_,i)=>m&(1<<i))); } none.forEach(k=>subsets.push([k])); return subsets; });
  const results=new Map(); let combos=0;
  const rec=(i,answers)=>{ if(i===Q.length){ combos++; const value=k=>{const q=Q[k],a=answers[k]; return q.multi? a.reduce((s,idx)=>s+(q.opts[idx][1]||0),0) : (q.opts[a[0]]?q.opts[a[0]][1]:0);}; const chosen=(k,label)=>answers[k].some(idx=>Q[k].opts[idx][0]===label); let score=0,flags=[]; Q.forEach((q,k)=>{const v=value(k); score+=v; if(q.flag&&v>=(q.flagAt||4)) flags.push(q.flag);}); const r=cfg.result({score,flags,value,chosen,PHONE:'901-390-2930'}); const key=[r.tier,r.label,r.text,r.urgent||'',(r.flags||[]).join('|'),r.cta1||''].join('\u0001'); if(!results.has(key)) results.set(key,{r,count:0,minScore:score,maxScore:score}); const e=results.get(key); e.count++; e.minScore=Math.min(e.minScore,score); e.maxScore=Math.max(e.maxScore,score); return;} for(const c of choiceSets[i]) rec(i+1,[...answers,c]); };
  rec(0,[]);
  out+=`<section class="vq-card" id="${slug}"><h2>${esc(title)} <small>(${slug}/ — ${Q.length} questions, ${combos.toLocaleString()} answer combinations, ${results.size} distinct results)</small></h2>`;
  out+='<h3>Questions and points</h3><ol class="qs">'+Q.map(q=>`<li><strong>${esc(q.q)}</strong>${q.multi?' <em>(choose all that apply)</em>':''}${q.help?`<br><span class="help">${esc(q.help)}</span>`:''}<ul>${q.opts.map(o=>`<li>${esc(o[0])} <span class="pts">${o[1]} pt${o[1]===1?'':'s'}</span>${o[2]==='none'?' <span class="pts">(exclusive)</span>':''}</li>`).join('')}</ul>${q.flag?`<div class="flagnote">⚑ Flag when ≥${q.flagAt||4} pts: “${esc(q.flag)}”</div>`:''}</li>`).join('')+'</ol>';
  out+='<h3>Every possible result</h3><table><tr><th>Tier</th><th>Label</th><th>Result text shown to the patient</th><th>Extra line</th><th>Score range</th></tr>'+[...results.values()].sort((a,b)=>({high:0,info:1,mod:2,low:3}[a.r.tier]-{high:0,info:1,mod:2,low:3}[b.r.tier])).map(({r,minScore,maxScore})=>`<tr><td><span class="vq-tier ${r.tier}">${r.tier}</span></td><td><strong>${esc(r.label)}</strong>${r.cta1?`<br><small>button: ${esc(r.cta1)}</small>`:''}</td><td>${esc(r.text)}${(r.flags&&r.flags.length)?'<ul>'+r.flags.map(f=>`<li>${esc(f)}</li>`).join('')+'</ul>':''}</td><td>${esc(r.urgent||'')}</td><td>${minScore===maxScore?minScore:minScore+'–'+maxScore}</td></tr>`).join('')+'</table>';
  out+=`<p class="help">Disclaimer shown under every result: “${esc(cfg.disclaimer)} If you have sudden severe symptoms, call 911. Your answers stay in your browser and are not sent to us.”</p></section>`;
}
const page=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Quiz wording review — all questions and results</title>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500;600;700&family=Barlow+Semi+Condensed:wght@400;500;600&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/quiz.css">
<style>.wrap{max-width:1100px}section{margin:0 0 28px}h2 small{font-size:.55em;color:#5a6b7c;font-weight:500}table{border-collapse:collapse;width:100%;font-size:.95em}th,td{border:1px solid #dfe6ee;padding:8px;vertical-align:top;text-align:left}th{background:#f4f7fb}.qs li{margin:0 0 8px}.qs ul{margin:4px 0 6px}.pts{color:#5a6b7c;font-size:.9em}.help{color:#5a6b7c;font-size:.95em}.flagnote{color:#9b1c1c;font-size:.92em;margin:4px 0}.vq-tier{margin:0}nav a{margin-right:14px}</style></head>
<body><header><div class="wrap top"><a href="https://vascularandveininstitute.com/"><img src="https://s43932.pcdn.co/wp-content/uploads/sites/190/2024/02/Flat-Horizontal-VVIS.png" alt="VVIS"></a><a class="back" href="../">All quizzes &rarr;</a></div></header>
<main class="wrap"><h1>Quiz wording review</h1><p class="lead">Internal review page (not indexed). For each quiz: every question with its answer points, then every distinct result the quiz can produce, found by running all answer combinations. Generated ${new Date().toISOString().slice(0,10)}.</p>
<nav>${slugs.map(s=>`<a href="#${s}">${s}</a>`).join('')}</nav>
${out}</main></body></html>`;
fs.writeFileSync('review/index.html',page); console.log('review page written');
